---
title: "R on a Server"
layout: default
output: bookdown::html_chapter
---

# R on a Server

Very large amounts of computation power can be rented in the cloud very inexpensively. If you are working on a machine that is not very powerful, or even if you have a reasonably powerful computer and prefer to execute long running processes somewhere else, it makes sense to take advantage of the power of cloud computing. In particular, R is limited by the amount of RAM on a machine, since it stores all data in memory. On machines with 8GB or fewer this can sometimes be a problem with very large data sets, especially geospatial data. But it is easy to rent extraordinary amounts of RAM on a server.

A mark of a good programmer is her ability to work within the constraints of the machine: RAM and processor. But you want to be a good historian, not a programmer.  Optimization takes a tremendous amount of work, and it is seldom cost-effective for you. 

## EC2 (or other Cloud Provider)

How to set up R and/or RStudio Server on an Amazon EC2 instance.

## Developing locally in Vagrant

