---
title: "Setting up R"
layout: default
output: bookdown::html_chapter
---

# Setting up R

## Installing R

## Installing R Studio

## Packages and Libraries

A **package** is a collection of R files bundled together to accomplish a particular purpose. Usually these packages provide a set of functions to provide a particular kind of analysis. The [dplyr](http://cran.rstudio.com/web/packages/dplyr/) package, for example, provides a set of functions for manipulating data, and the [rgdal](http://cran.rstudio.com/web/packages/rgdal/) package provides a set of functions for working with geospatial files. Because R is especially good at data analysis, it is also common to provide data packages which wrap generally useful datasets. R has a built in [datasets](http://stat.ethz.ch/R-manual/R-devel/library/datasets/html/00Index.html) package which provides a set of sample datasets, and the [babynames](https://github.com/hadley/babynames) package provides data about births from the Social Security Administration.^[For a fuller description of packages, see the introduction and chapter 1 of Hadley Wickham, *[R Packages](http://r-pkgs.had.co.nz/)* (O'Reilly, forthcoming).]

A **library** is a collection of packages stored on your computer. R has a built-in library which stores the packages which come bundled with base R. You will also create a personal package library which stores the packages that you have installed. You needn't worry about where this library is on your computer: R will prompt you for permission to create it the first time that you install packages. (You can find where it is by running the function `.libPaths()`. When you work on specific analysis projects, it is desirable to keep a separate library of packages uses just for that project in the project directory. This will ensure that you can later re-run your analysis. This can be managed using the [Packrat](http://rstudio.github.io/packrat/) package, which we'll cover later. (See the chapter on [reproducible research](reproducible.html).)

## Starter packages and libraries

You won't get very far in doing historical work with R without installing a few packages. This section will guide you in installing a few basic packages which you can't live without. Then it will suggest some packages categorized by the type of analysis that you wish to do.

There are two main places from which you can install packages. [CRAN](http://cran.rstudio.com/), the Comprehensive R Archive Network, is a central repository of R packages.^[There are other CRAN-like repositories, such as [Bioconductor](http://www.bioconductor.org/) which provide discipline specific packages, but these are all for scientists.] To be published on CRAN, packages have to go through a rigorous testing process. You can be fairly confident that a CRAN package is, technically speaking at least, reliable. R users also have a culture oriented around academic research, so you can be more confident with CRAN packages than with the repositories for most languages that the functions provided are academically rigorous, and in some cases at least, peer reviewed. CRAN provides a wide array of packages, for statistics, business, science, social science, geospatial analysis, network analysis, text mining, natural language processing, visualization, and other domains. Most of the packages are not targeted specifically at historians (you can help change this!) but many can be used by historians. You can browse the [list of packages available at CRAN by name](http://cran.rstudio.com/web/packages/available_packages_by_name.html), or can browse the [task views](http://cran.rstudio.com/web/views/) which provide guides to packages relevant to a particular analytical technique.

## Citing packages

## .Rprofile
